<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Services\ClienteService;
use Illuminate\Database\Seeder;

class ClienteSeeder extends Seeder
{
    public function run(): void
    {
        $service = app(ClienteService::class);

        $clientes = [
            [
                'dni' => 41000001,
                'nombre' => 'Juan',
                'apellido' => 'Perez',
                'telefono' => '3815551001',
                'peso' => 72.50,
                'altura' => 1.74,
                'observaciones' => 'Cliente de entrenamiento general',
                'estado' => true,
            ],
            [
                'dni' => 41000002,
                'nombre' => 'Maria',
                'apellido' => 'Gonzalez',
                'telefono' => '3815551002',
                'peso' => 63.20,
                'altura' => 1.62,
                'observaciones' => 'Asiste por la manana',
                'estado' => true,
            ],
            [
                'dni' => 41000003,
                'nombre' => 'Lucas',
                'apellido' => 'Diaz',
                'telefono' => '3815551003',
                'peso' => 81.10,
                'altura' => 1.80,
                'observaciones' => 'Prioridad en rutina de fuerza',
                'estado' => true,
            ],
            [
                'dni' => 41000004,
                'nombre' => 'Camila',
                'apellido' => 'Ramirez',
                'telefono' => '3815551004',
                'peso' => 58.40,
                'altura' => 1.59,
                'observaciones' => null,
                'estado' => true,
            ],
            [
                'dni' => 41000005,
                'nombre' => 'Martin',
                'apellido' => 'Lopez',
                'telefono' => '3815551005',
                'peso' => 77.80,
                'altura' => 1.77,
                'observaciones' => 'Retoma actividad fisica',
                'estado' => true,
            ],
            [
                'dni' => 41000006,
                'nombre' => 'Sofia',
                'apellido' => 'Torres',
                'telefono' => '3815551006',
                'peso' => 55.30,
                'altura' => 1.60,
                'observaciones' => 'Plan de cardio y movilidad',
                'estado' => true,
            ],
            [
                'dni' => 41000007,
                'nombre' => 'Diego',
                'apellido' => 'Acosta',
                'telefono' => '3815551007',
                'peso' => 84.90,
                'altura' => 1.83,
                'observaciones' => 'Entrenamiento deportivo',
                'estado' => true,
            ],
            [
                'dni' => 41000008,
                'nombre' => 'Valentina',
                'apellido' => 'Sanchez',
                'telefono' => '3815551008',
                'peso' => 60.20,
                'altura' => 1.65,
                'observaciones' => null,
                'estado' => true,
            ],
            [
                'dni' => 41000009,
                'nombre' => 'Nicolas',
                'apellido' => 'Fernandez',
                'telefono' => '3815551009',
                'peso' => 79.40,
                'altura' => 1.79,
                'observaciones' => 'Plan de hipertrofia',
                'estado' => true,
            ],
            [
                'dni' => 41000010,
                'nombre' => 'Agustina',
                'apellido' => 'Ruiz',
                'telefono' => '3815551010',
                'peso' => 57.10,
                'altura' => 1.61,
                'observaciones' => 'Control de progreso mensual',
                'estado' => true,
            ],
            [
                'dni' => 41000011,
                'nombre' => 'Pablo',
                'apellido' => 'Vega',
                'telefono' => '3815551011',
                'peso' => 88.60,
                'altura' => 1.84,
                'observaciones' => 'Ingreso reciente',
                'estado' => true,
            ],
            [
                'dni' => 41000012,
                'nombre' => 'Julieta',
                'apellido' => 'Morales',
                'telefono' => '3815551012',
                'peso' => 54.90,
                'altura' => 1.58,
                'observaciones' => null,
                'estado' => true,
            ],
            [
                'dni' => 41000013,
                'nombre' => 'Federico',
                'apellido' => 'Castro',
                'telefono' => '3815551013',
                'peso' => 76.30,
                'altura' => 1.76,
                'observaciones' => 'Plan combinado',
                'estado' => true,
            ],
            [
                'dni' => 41000014,
                'nombre' => 'Carla',
                'apellido' => 'Ortiz',
                'telefono' => '3815551014',
                'peso' => 61.00,
                'altura' => 1.63,
                'observaciones' => 'Rutina de bienestar',
                'estado' => true,
            ],
            [
                'dni' => 41000015,
                'nombre' => 'Gabriel',
                'apellido' => 'Medina',
                'telefono' => '3815551015',
                'peso' => 83.70,
                'altura' => 1.82,
                'observaciones' => 'Trabaja con cargas progresivas',
                'estado' => true,
            ],
            [
                'dni' => 41000016,
                'nombre' => 'Micaela',
                'apellido' => 'Silva',
                'telefono' => '3815551016',
                'peso' => 59.80,
                'altura' => 1.64,
                'observaciones' => null,
                'estado' => true,
            ],
            [
                'dni' => 41000017,
                'nombre' => 'Joaquin',
                'apellido' => 'Herrera',
                'telefono' => '3815551017',
                'peso' => 80.90,
                'altura' => 1.81,
                'observaciones' => 'Plan mensual intensivo',
                'estado' => true,
            ],
            [
                'dni' => 41000018,
                'nombre' => 'Noelia',
                'apellido' => 'Romero',
                'telefono' => '3815551018',
                'peso' => 52.70,
                'altura' => 1.57,
                'observaciones' => 'Sesiones cortas',
                'estado' => true,
            ],
            [
                'dni' => 41000019,
                'nombre' => 'Tomas',
                'apellido' => 'Rojas',
                'telefono' => '3815551019',
                'peso' => 74.20,
                'altura' => 1.75,
                'observaciones' => 'Enfoque en resistencia',
                'estado' => true,
            ],
            [
                'dni' => 41000020,
                'nombre' => 'Luciana',
                'apellido' => 'Navarro',
                'telefono' => '3815551020',
                'peso' => 56.80,
                'altura' => 1.60,
                'observaciones' => null,
                'estado' => true,
            ],
            [
                'dni' => 41000021,
                'nombre' => 'Bruno',
                'apellido' => 'Ibarra',
                'telefono' => '3815551021',
                'peso' => 86.40,
                'altura' => 1.85,
                'observaciones' => 'Requiere seguimiento nutricional',
                'estado' => true,
            ],
            [
                'dni' => 41000022,
                'nombre' => 'Rocio',
                'apellido' => 'Mendez',
                'telefono' => '3815551022',
                'peso' => 53.90,
                'altura' => 1.58,
                'observaciones' => 'Registra asistencia constante',
                'estado' => true,
            ],
            [
                'dni' => 41000023,
                'nombre' => 'Ezequiel',
                'apellido' => 'Paz',
                'telefono' => '3815551023',
                'peso' => 78.10,
                'altura' => 1.78,
                'observaciones' => 'Cliente con plan semanal',
                'estado' => true,
            ],
            [
                'dni' => 41000024,
                'nombre' => 'Antonella',
                'apellido' => 'Leiva',
                'telefono' => '3815551024',
                'peso' => 58.60,
                'altura' => 1.62,
                'observaciones' => null,
                'estado' => true,
            ],
        ];

        foreach ($clientes as $cliente) {
            $service->crearCliente($cliente);
        }
    }
}
